name: .NET

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Nuget
      id: cache-nuget
      uses: actions/cache@v2
      with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: cd date_component.tests && dotnet restore
    - name: Build
      run: cd date_component.tests && dotnet build --no-restore
    - name: Test
      run: cd date_component.tests && dotnet test --no-build --verbosity normal
